🚀 로그인에 refresh token 기능 적용
Team-SilverTown/Team-SilverTown-MasilGasil-BE pull request #136
Opened 2024-03-16 18:32 UTC by shoeone96

## 🎫 관련 이슈

*Resolves #126 

## 🚀 주요 변경사항
- `refresh token`으로 `access token`을 재발급하는 api 토큰 만들기
    - `api/v1/users/login/refresh`
### 방식
- 로그인 시 refresh token과 memberId 정보를 Redis에 저장
- Redis에 TTL로 refresh token 유효시간 설정
- 로그인 response로 기존에 반환하던 access token 이외에도 refresh token까지 반환
- token 만료되어 401에러가 프론트에서 날 시 refresh 요청을 서버에 보냄
- access token과 refresh token 검증 뒤 Redis에서 refresh token 검색
- refresh token 정보로 새롭게 access token 생성
- 생성된 access token을 header에 담아서 response로 반환

## 💡 기타사항

2024-03-17 05:14 UTC, IjjS reviewed
고생하셨습니다!! 로직을 점점 더 잘 짜시는 것 같아요

2024-03-17 05:14 UTC, IjjS commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +    }
로그인 응답은 유저 패키지에 머물러서 응집하는게 낫다고 생각하는데 어떻게 생각하시나요?

2024-03-17 05:14 UTC, IjjS commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +    private String createRefreshToken(Long userId) {
refresh token expiration은 없는거로 가나요?

2024-03-17 05:14 UTC, IjjS commented on src/main/java/team/silvertown/masil/user/controller/UserController.java
> +    }
이 부분도 서비스로 내리면 어떨까요? request 관련이라 컨트롤러에서 처리하신걸까요?

2024-03-17 05:14 UTC, IjjS commented on src/main/java/team/silvertown/masil/user/dto/RefreshTokenRequest.java
이 객체는 어디 쓰이나요??

2024-03-17 05:14 UTC, IjjS commented on src/main/java/team/silvertown/masil/user/service/UserService.java
> +            refreshTokenRepository.save(new RefreshToken(loginResponse.refreshToken(), user.get()
이렇게 보니까 인증/인가가 유저 서브도메인으로 들어가거나 인증/안가랑 유저를 분리해서 도메인을 생각해야 하나 생각도 드네요.. 지금은 괜찮습니다!!

2024-03-17 05:14 UTC, IjjS commented on src/main/java/team/silvertown/masil/user/service/UserService.java
> +            .orElseThrow(() -> new DataNotFoundException(UserErrorCode.REFRESH_TOKEN_NOT_FOUND));
리프레시 토큰이 두개 이상 생기면 어떻게 되나요??

2024-03-17 05:39 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +    }
이거 고민해봤는데 login, refresh를 아예 TokenController를 만들어서 빼는 건 어때요?
유저 쪽이랑 연관되어 있긴 한데 둘 다 결국 요청하는 게 토큰이라 그렇게 빼는 방법도 생각해보긴 했어요

그게 아니라면 createAccessToken과 createRefreshToken 메서드를 가지고 userService에서 사용해서 토큰을 반환하는 방식도 괜찮은 것 같아요

2024-03-17 05:40 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +    private String createRefreshToken(Long userId) {
이거는 redis ttl로만 가져가서 시간이 지나면 redis에서 refreshtoken 정보가 삭제되고 더 이상 사용할 수 없으니까 굳이 refresh token에 expiration을 넣지 않아도 되지 않을까라고 생각했어요!

2024-03-17 05:41 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/user/controller/UserController.java
> +    }
네네 맞아요 뭔가 서비스에서 정확히 토큰 값만 받고 처리하는 게 로직상 더 좋아보여서 그렇게 처리하긴 했어요
서비스에서 하는 게 더 로직 상 좋을까요??

2024-03-17 05:42 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/user/dto/RefreshTokenRequest.java
아 이건 삭제하겠습니다 원래는 토큰을 바디로 받았어서 사용했다가 헤더로 받는 방식으로 변경하면서 지웠어야 했는데 눈치를 못채고 있었어요

2024-03-17 05:43 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/user/service/UserService.java
> +            refreshTokenRepository.save(new RefreshToken(loginResponse.refreshToken(), user.get()
[이 부분](https://github.com/Team-SilverTown/Team-SilverTown-MasilGasil-BE/pull/136#discussion_r1527417238
) 의견 한번 주세요!

2024-03-17 05:45 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/user/service/UserService.java
> +            .orElseThrow(() -> new DataNotFoundException(UserErrorCode.REFRESH_TOKEN_NOT_FOUND));
아 확실히 동일한 아이디로 다른 곳에서 로그인하면 그렇게 될 수 있겠네요.. 동시 로그인도 막을겸 이미 값이 있으면 예외를 터뜨리거나 기존의 거를 삭제하거나 할까요? 아니면 expiration없이 발행 시간은 넣으면 토큰의 유일성을 유지할 수 있을 것 같은데 어떤가요?

2024-03-17 05:49 UTC, IjjS commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +    }
괜찮은 것 같아요! token이던 auth이던 원하시는 방향으로 진행하시면 될 것 같습니다

2024-03-17 05:51 UTC, IjjS commented on src/main/java/team/silvertown/masil/user/controller/UserController.java
> +    }
request의 헤더를 처리하는거니 서비스에 들어가기 애매해 보이기도 하고.. 컨트롤러에 이만한 로직이 들어가는게 생소해보이기도 하고.. 필터를 만들고 `@AuthenticationPrincipal` 비슷한 애너테이션을 만들 수도 있을 것 같은데 과한가 싶기도 하고.. 완벽한건 없어 보이네요..!! 컨트롤러에서 처리하는게 나을 것 같아 보이기도 해요!

2024-03-17 05:57 UTC, IjjS commented on src/main/java/team/silvertown/masil/user/service/UserService.java
> +            .orElseThrow(() -> new DataNotFoundException(UserErrorCode.REFRESH_TOKEN_NOT_FOUND));
발행 시간 넣는게 좋아보입니다!

2024-03-19 01:47 UTC, IjjS reviewed
고생하셨습니다!

2024-03-19 01:47 UTC, IjjS commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +    private final KakaoOAuthService kakaoOAuthService;
얘도 auth에 들어가있는게 낫지 않을까요?

2024-03-19 01:47 UTC, IjjS commented on src/main/java/team/silvertown/masil/auth/controller/AuthController.java
> +            .header(HttpHeaders.AUTHORIZATION, ACCESS_TOKEN_PREFIX + newToken)
프리픽스 붙이는 걸 서비스에서 해도 될 것 같습니다! 근데 저희 로그인 시에는 바디로 내려주고 리프레시는 헤더로 내려주나요?

2024-03-19 01:47 UTC, IjjS commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +    }
여기 코멘트는 반영이 안된 것 같습니다! jwt도 auth로 옮기거나 아니면 createAccessToken이랑 createRefreshToken을 따로 내려서 LoginResponse를 auth 도메인에만 머무르게 하는건 어떨까요??

2024-03-19 01:47 UTC, IjjS commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +    private void validateToken(String accessToken, String refreshToken) {
👍

2024-03-19 01:47 UTC, IjjS commented on src/test/java/team/silvertown/masil/user/controller/UserControllerTest.java
지워주세요 ㅎㅎ

2024-03-19 01:47 UTC, IjjS commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +        LoginResponse loginResponse = tokenProvider.createToken(justSavedUser.getId(), authorities);
이 부분 뭔가 밑에 joinedUserResponse를 그대로 쓸 수 있을 것만 같네요

2024-03-19 01:47 UTC, IjjS commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +        return tokenProvider.createAccessToken(user.getId(), userAuthorities);
이 부분도 밑에 함수를 쓸 수 있을 것 같아요

2024-03-19 02:05 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/auth/controller/AuthController.java
> +            .header(HttpHeaders.AUTHORIZATION, ACCESS_TOKEN_PREFIX + newToken)
네 맞습니다! 이렇게 해놓으면 별도로 프론트에서 다른 로직 사용할 거 없이 그대로 토큰 사용할 수 있을 것 같아서요

2024-03-19 02:05 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +    private final KakaoOAuthService kakaoOAuthService;
여기서 OAuthService 말씀이신 가요 아니면 그 위에 세 개를 다 말씀하시는 건가요?

2024-03-19 02:07 UTC, IjjS commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +    private final KakaoOAuthService kakaoOAuthService;
카카오 서비스요!

2024-03-19 07:25 UTC, ASak1104 reviewed
고생하셨어요 형님!! 리뷰가 늦어서 죄송합니다

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/controller/AuthController.java
> +    public ResponseEntity<Void> refresh(
개행이 있어요 형님!

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/controller/AuthController.java
> +            .header(HttpHeaders.AUTHORIZATION, ACCESS_TOKEN_PREFIX + newToken)
`service`는  말 그대로 토큰을 생성하는 로직을 담당하니까
저는 지금처럼 헤더 설정을 controller에서 하는게 좋아보입니다!

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/domain/RefreshToken.java
> +    private Long memberId;
도메인이니까 개행하는게 좋아보여요!

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +        User justSavedUser = userService.createAndSave(provider, oAuthResponse.providerId());
변수명이 `justSavedUser` 인 이유가 있나요?

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +        validateToken(accessToken, refreshToken);
이거 순서가 바뀌지 않았나요?

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +            .orElseThrow(() -> new DataNotFoundException(UserErrorCode.REFRESH_TOKEN_NOT_FOUND));
토큰 없어지면 404말고 다른 에러로 처리해야되지 않을까요?
아무래도 헤더 값으로 판단을 하는거니까 서버 리소스로 보기 어려운 것 같아서요
400은 어떨까요?

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +    }
형님들 `createToken` 메서드를 2개로 분리하는게 좋아보이지 않나요?
그냥 이 함수를 없애고 서비스에서 create 메서드 2개를 각각 호출하는게 좋아보이는데요?

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +            .compact();
`fm`으로 하면 `ttl`이 있긴 해야죠
원주님께서 토큰 payload를 직접 분석하고 싶어하시는 것 같은데 이야기를 해봐야겠네요
만약 프론트에서 payload를 뜯어서 task를 만든다면 refresh 토큰이 만료되었을 때의
프론트 쪽 미들웨어에서 예외처리가 힘들기도 하고요

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +    }
이거 어디서 쓰나요 형님?

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
> +    private static final String AUTH_RESOURCE = "/api/v1/auth/**";
👍

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/user/exception/UserErrorCode.java
> +    REFRESH_TOKEN_NOT_FOUND(10020402, "해당 refresh token을 찾을 수 없습니다.");
이거랑 `INVALID_JWT_TOKEN`은 `AuthErrorCode`로 빠지면 좋을 것 같아요

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/user/service/KakaoOAuthService.java
> +            log.error("social login error occured, the reason is: {}", e.getMessage(), e);
테스트 로깅하신 이유가 있나요??

2024-03-19 07:25 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/user/service/UserService.java
> +    public User createAndSave(Provider authenticatedProvider, String providerId) {
이런 부분을 보면 동일 서비스 레이어 참조 보다 DAO로 하는게 예쁘게 나오긴 하겠네요

2024-03-19 07:25 UTC, ASak1104 commented on src/test/java/team/silvertown/masil/user/controller/UserControllerTest.java
아직 안지워진 것 같아서 제가 지울게요

2024-03-19 07:33 UTC, IjjS commented on src/main/java/team/silvertown/masil/auth/controller/AuthController.java
> +            .header(HttpHeaders.AUTHORIZATION, ACCESS_TOKEN_PREFIX + newToken)
헤더 설정은 컨트롤러에서 하는게 맞는 것 같은데 프리픽스 붙이는 걸 bearer 토큰 생성의 일부라고 생각했어서 서비스나 프로바이더 로직이 더 맞다고 생각하긴 합니다. 사실 큰 부분이 아니라 지금 같이 막바지면 넘어가도 될 것 같아요

2024-03-19 07:38 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/controller/AuthController.java
> +            .header(HttpHeaders.AUTHORIZATION, ACCESS_TOKEN_PREFIX + newToken)
프로바이더 로직이 맞네요!
저도 큰 상관 없습니당

2024-03-19 08:03 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +    }
아 그걸로 마침 작성하고 있었어요 👍

2024-03-19 08:15 UTC, shoeone96 commented on src/test/java/team/silvertown/masil/user/controller/UserControllerTest.java
다음 커밋 반영에 올라가고 있긴했었는데 어느 쪽이든 반영되면 될 것 같아요

2024-03-19 08:16 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +        LoginResponse loginResponse = tokenProvider.createToken(justSavedUser.getId(), authorities);
joinedUserResponse는 Response값을 주는 거고 저기는 accessToken만 만들어서 반환하는 로직이라 구분했어요!

2024-03-19 08:17 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +    }
이거 삭제했어요

2024-03-19 08:27 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +            .compact();
아까 원주님이 말씀하신 건 accessToken 쪽 ttl 얘기한 걸로 알고 있어서 이쪽 ttl은 고려하지 않아도 되지 않을까요?
넣는 거에 대해 반대하진 않는데 아마 refresh 로직에서는 검증 안하고 보낼 것 같은데
refresh 로직에서는 아까 얘기나온 일정 시간 지날 때마다로 토큰 payload 검사하기에는 기간이 많이 길어서 그 방법도 힘들 것 같아서요

2024-03-19 08:31 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +            .orElseThrow(() -> new DataNotFoundException(UserErrorCode.REFRESH_TOKEN_NOT_FOUND));
Redis db에 있는 RefreshToken Resource ttl 때문에 없어져서 로직을 수행 못하는 걸로 생각해 404로 내리긴 했는데
그래도 BadRequest가 나을까요?

2024-03-19 08:32 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +        User justSavedUser = userService.createAndSave(provider, oAuthResponse.providerId());
이미 가입되어 있는 user랑 이제 막 저장된 로그인 유저를 구분하고 싶어서 수정했었어요!

2024-03-19 08:57 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/user/service/KakaoOAuthService.java
> +            log.error("social login error occured, the reason is: {}", e.getMessage(), e);
저기서 막히는 부분이 생기면 로그인, 회원가입이 모두 막힐 것 같아서 로깅을 남기는 게 필요하다고 생각하긴 했는데 
굳이 필요없다고 생각하면 넘겨도 될 것 같아요

2024-03-19 09:17 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +        User justSavedUser = userService.createAndSave(provider, oAuthResponse.providerId());
그러면 `justSavedUser` 보다 `newSavedUser`가 더 좋은 것 같아요!

2024-03-19 09:18 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +            .orElseThrow(() -> new DataNotFoundException(UserErrorCode.REFRESH_TOKEN_NOT_FOUND));
저는 URI가 아니라 Header 데이터를 가지고 판단하니까 `400`이 더 좋아보여요!

2024-03-19 09:20 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +            .compact();
원주님께서 말씀해주신 로직으로 하려면 refreshToken도 `ttl`이 있어야 되니까
한 번 토의해보신 다음에 정하면 될 것 같아요
refreshToken에 대해서도 무조건 버그가 생길테니까요!
개인적으로는 `401` 튕겨낸 다음에 처리하는 프론트 로직이 훨씬 깔끔하다고 생각이 들어서 바꿨으면 합니다!

2024-03-19 09:21 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/user/service/KakaoOAuthService.java
> +            log.error("social login error occured, the reason is: {}", e.getMessage(), e);
넵넵 좋습니다 형님~

2024-03-19 09:21 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/user/service/UserService.java
> +    public User createAndSave(Provider authenticatedProvider, String providerId) {
크게 상관 없어서 resolve 하겠습니다!

2024-03-19 09:22 UTC, IjjS commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +        LoginResponse loginResponse = tokenProvider.createToken(justSavedUser.getId(), authorities);
저 메서드가 authorities들이랑 토큰을 만드는 메서드라서 메서드 내용이 변경되거나 아니면 메서드 명을 변경해서 써도 될 것 같아보입니다!!

2024-03-19 09:23 UTC, IjjS commented on src/main/java/team/silvertown/masil/user/service/KakaoOAuthService.java
> +            log.error("social login error occured, the reason is: {}", e.getMessage(), e);
카카오 로그인이 막히는 거면 로깅을 하는게 좋을 것 같아보여요

2024-03-19 12:05 UTC, IjjS approved these changes

2024-03-19 12:08 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +            .compact();
401 튕겨내면 일단 무조건 로그인 페이지로 리다이렉트 시키시는 방향을 생각하신 것 같았는데
우선 이 로직에서 프론트 분들 처리하는 상황을 보고 추후에 변경해도 좋을 것 같아요!

2024-03-19 12:18 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/auth/service/AuthService.java
> +        LoginResponse loginResponse = tokenProvider.createToken(justSavedUser.getId(), authorities);
음 access token 만들 때 필수 정보라서 createAccessToken 정도로 만들긴 했는데 저기서 뭔가 더 빼면 과해 보이는 느낌이 들어서 이정도로 하면 조금 이상할까요?

2024-03-19 12:18 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +            .compact();
만약에 payload를 분석하는 방식이면 지금이라도 ttl을 적용해야할 것 같아서요
exp 필드가 없는 refreshToken 에서 버그가 무조건 생기는 방식이라 조금 걱정이 됩니다

2024-03-19 12:34 UTC, shoeone96 commented on src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
> +            .compact();
추가하고 dev, prod 환경변수에도 추가했습니다

2024-03-19 12:40 UTC, IjjS approved these changes

2024-03-19 12:40 UTC, IjjS commented on src/main/resources/application.yml
> +  refresh-token-validity-in-seconds: ${REFRESH_TOKEN_EXPIRATION}
토큰명 시크릿에 적용하는거 잊지 말아주십쇼!!

2024-03-19 12:42 UTC, shoeone96 commented on src/main/resources/application.yml
> +  refresh-token-validity-in-seconds: ${REFRESH_TOKEN_EXPIRATION}
dev랑 prod 환경변수에 모두 추가 완료했습니다!

2024-03-19 12:42 UTC, ASak1104 requested changes
cd action 스크립트 쪽만 수정하면 될 것 같아요!

2024-03-19 12:42 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/domain/RefreshToken.java
> +    private Long memberId;
필드 사이 개행은 따로 안하는 걸로 생각하신거죠?
알겠습니당

2024-03-19 12:42 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/exception/AuthErrorCode.java
> +    }
lombok annotation 사용하시죠!

2024-03-19 12:42 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/exception/AuthErrorCode.java
> +        "Access Denied: Authentication token was either missing or invalid.");
prefix를 100에서 101 같은 걸로 해도 좋겠네요

2024-03-19 12:42 UTC, ASak1104 commented on src/main/java/team/silvertown/masil/auth/service/KakaoOAuthService.java
> +        HashMap<String, Object> userInfo = new HashMap<>();
```suggestion
        Map<String, Object> userInfo = new HashMap<>();
```

2024-03-19 12:42 UTC, ASak1104 commented on src/main/resources/application.yml
> +  refresh-token-validity-in-seconds: ${REFRESH_TOKEN_EXPIRATION}
형님 CD action 이랑 github secrets에 추가가 됐을까요?

2024-03-19 12:43 UTC, IjjS commented on src/main/resources/application.yml
> +  refresh-token-validity-in-seconds: ${REFRESH_TOKEN_EXPIRATION}
cd 에도요!!

2024-03-19 12:51 UTC, shoeone96 commented on src/main/resources/application.yml
> +  refresh-token-validity-in-seconds: ${REFRESH_TOKEN_EXPIRATION}
마지막 커밋 한번 봐주세요

@ASak1104 @IjjS

2024-03-19 12:53 UTC, IjjS approved these changes

2024-03-19 12:59 UTC, ASak1104 approved these changes
고생하셨습니다!
dev로 머지될 때 `TOKEN_EXPIRATION` 만 지우면 될 것 같아요!

2024-03-19 13:02 UTC, merged